// lib/infrastructure/gamification/datasources/c2b_gamification_task_local_source.dart
import 'package:meetclic_app/domain/gamification/entities/c2b_gamification_task.dart';

class C2BGamificationTaskLocalSource {
  C2BGamificationTaskLocalSource();

  List<C2BGamificationTask> getAll() => _data;

  // aquí tu lista:
  static final List<C2BGamificationTask> _data = [
    // =====================================================
    // 1) INTERACCIÓN CON LA EMPRESA (groupId = 1, 20 puntos)
    // typePoints = "yapitas"
    // =====================================================
    C2BGamificationTask(
      id: 151,
      code: 'C2B-01',
      name: 'Seguir negocio para fortalecer relación',
      description:
          'Seguir negocio para fortalecer relación y recibir novedades',
      groupId: 1,
      groupName: 'Interacción con la empresa',
      gamificationTypeActivityId: 2,
      gamificationTypeActivityName: 'Suscribirse',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: false,
      startDate: null,
      endDate: null,
      points: 20,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 152,
      code: 'C2B-02',
      name: 'Visitar perfil de negocio para conocer detalles',
      description:
          'Visitar perfil de negocio para conocer detalles de productos y servicios',
      groupId: 1,
      groupName: 'Interacción con la empresa',
      gamificationTypeActivityId: 11,
      gamificationTypeActivityName: 'Marketing',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: false,
      startDate: null,
      endDate: null,
      points: 20,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 153,
      code: 'C2B-03',
      name: 'Guardar negocio como favorito para acceso rápido',
      description:
          'Guardar negocio como favorito para acceso rápido y seguimiento futuro',
      groupId: 1,
      groupName: 'Interacción con la empresa',
      gamificationTypeActivityId: 11,
      gamificationTypeActivityName: 'Marketing',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: false,
      startDate: null,
      endDate: null,
      points: 20,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 154,
      code: 'C2B-04',
      name: 'Compartir negocio en redes para aumentar visibilidad',
      description:
          'Compartir negocio en redes para aumentar visibilidad y atraer nuevos clientes',
      groupId: 1,
      groupName: 'Interacción con la empresa',
      gamificationTypeActivityId: 1,
      gamificationTypeActivityName: 'Share',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: false,
      startDate: null,
      endDate: null,
      points: 20,
      typePoints: 'yapitas',
      sourceUrl: 'https://meetclic.com/share',
    ),
    C2BGamificationTask(
      id: 155,
      code: 'C2B-05',
      name: 'Visitar tienda física para validar presencia',
      description:
          'Visitar tienda física para validar presencia del negocio y reforzar confianza',
      groupId: 1,
      groupName: 'Interacción con la empresa',
      gamificationTypeActivityId: 11,
      gamificationTypeActivityName: 'Marketing',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: false,
      startDate: null,
      endDate: null,
      points: 20,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 156,
      code: 'C2B-06',
      name: 'Leer noticias del negocio para mantenerse informado',
      description:
          'Leer noticias del negocio para mantenerse informado sobre novedades y promociones',
      groupId: 1,
      groupName: 'Interacción con la empresa',
      gamificationTypeActivityId: 11,
      gamificationTypeActivityName: 'Marketing',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: false,
      startDate: null,
      endDate: null,
      points: 20,
      typePoints: 'yapitas',
      sourceUrl: 'https://meetclic.com/news',
    ),

    // =====================================================
    // 2) COMPRA Y CONSUMO (groupId = 2, 100 puntos)
    // typePoints = "yapitas"
    // =====================================================
    C2BGamificationTask(
      id: 157,
      code: 'C2B-10',
      name: 'Realizar compra en negocio para generar venta',
      description:
          'Realizar compra en negocio para generar venta y apoyar crecimiento empresarial',
      groupId: 2,
      groupName: 'Compra y consumo',
      gamificationTypeActivityId: 5,
      gamificationTypeActivityName: 'Compra',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: false,
      startDate: null,
      endDate: null,
      points: 100,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 158,
      code: 'C2B-11',
      name: 'Comprar producto destacado para impulsar promoción',
      description:
          'Comprar producto destacado para impulsar promoción y aumentar rotación de inventario',
      groupId: 2,
      groupName: 'Compra y consumo',
      gamificationTypeActivityId: 5,
      gamificationTypeActivityName: 'Compra',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: false,
      startDate: null,
      endDate: null,
      points: 100,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 159,
      code: 'C2B-12',
      name: 'Suscribirse a plan del negocio para acceder beneficios',
      description:
          'Suscribirse a plan del negocio para acceder beneficios recurrentes y descuentos',
      groupId: 2,
      groupName: 'Compra y consumo',
      gamificationTypeActivityId: 5,
      gamificationTypeActivityName: 'Compra',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: true,
      startDate: DateTime(2025, 1, 1, 0, 0),
      endDate: DateTime(2025, 12, 31, 23, 59),
      points: 100,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 160,
      code: 'C2B-13',
      name: 'Pagar con MeetClic Pay para agilizar transacción',
      description:
          'Pagar con MeetClic Pay para agilizar transacción y mejorar experiencia de compra',
      groupId: 2,
      groupName: 'Compra y consumo',
      gamificationTypeActivityId: 6,
      gamificationTypeActivityName: 'Pagos',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: false,
      startDate: null,
      endDate: null,
      points: 100,
      typePoints: 'yapitas',
      sourceUrl: 'https://meetclic.com/pay',
    ),
    C2BGamificationTask(
      id: 161,
      code: 'C2B-14',
      name: 'Canjear cupón del negocio para obtener descuento',
      description:
          'Canjear cupón del negocio para obtener descuento y aprovechar promoción activa',
      groupId: 2,
      groupName: 'Compra y consumo',
      gamificationTypeActivityId: 5,
      gamificationTypeActivityName: 'Compra',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: true,
      startDate: DateTime(2025, 1, 1, 0, 0),
      endDate: DateTime(2025, 12, 31, 23, 59),
      points: 100,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 162,
      code: 'C2B-15',
      name: 'Completar compra recomendada para optimizar experiencia',
      description:
          'Completar compra recomendada para optimizar experiencia y recibir sugerencias personalizadas',
      groupId: 2,
      groupName: 'Compra y consumo',
      gamificationTypeActivityId: 5,
      gamificationTypeActivityName: 'Compra',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: false,
      startDate: null,
      endDate: null,
      points: 100,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),

    // =====================================================
    // 3) FEEDBACK (groupId = 3, 60 puntos)
    // typePoints = "yapitas"
    // =====================================================
    C2BGamificationTask(
      id: 163,
      code: 'C2B-20',
      name: 'Calificar negocio para aportar valoración',
      description:
          'Calificar negocio para aportar valoración y orientar a otros clientes',
      groupId: 3,
      groupName: 'Feedback',
      gamificationTypeActivityId: 8,
      gamificationTypeActivityName: 'Atención al Cliente',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: false,
      startDate: null,
      endDate: null,
      points: 60,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 164,
      code: 'C2B-21',
      name: 'Escribir reseña del negocio para orientar a clientes',
      description:
          'Escribir reseña del negocio para orientar a clientes y compartir experiencia personal',
      groupId: 3,
      groupName: 'Feedback',
      gamificationTypeActivityId: 8,
      gamificationTypeActivityName: 'Atención al Cliente',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: false,
      startDate: null,
      endDate: null,
      points: 60,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 165,
      code: 'C2B-22',
      name: 'Subir evidencia de compra para validar experiencia',
      description:
          'Subir evidencia de compra para validar experiencia y aumentar confiabilidad de la reseña',
      groupId: 3,
      groupName: 'Feedback',
      gamificationTypeActivityId: 8,
      gamificationTypeActivityName: 'Atención al Cliente',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: false,
      startDate: null,
      endDate: null,
      points: 60,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 166,
      code: 'C2B-23',
      name: 'Responder encuesta del negocio para mejorar servicio',
      description:
          'Responder encuesta del negocio para mejorar servicio y aportar información clave',
      groupId: 3,
      groupName: 'Feedback',
      gamificationTypeActivityId: 8,
      gamificationTypeActivityName: 'Atención al Cliente',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: true,
      startDate: DateTime(2025, 1, 1, 0, 0),
      endDate: DateTime(2025, 12, 31, 23, 59),
      points: 60,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 167,
      code: 'C2B-24',
      name: 'Reportar problema del negocio para corregir fallas',
      description:
          'Reportar problema del negocio para corregir fallas y proteger experiencia de otros clientes',
      groupId: 3,
      groupName: 'Feedback',
      gamificationTypeActivityId: 8,
      gamificationTypeActivityName: 'Atención al Cliente',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: false,
      startDate: null,
      endDate: null,
      points: 60,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),

    // =====================================================
    // 4) FIDELIZACIÓN (groupId = 4, 80 puntos)
    // typePoints = "yapitas"
    // =====================================================
    C2BGamificationTask(
      id: 168,
      code: 'C2B-30',
      name: 'Reclamar recompensa del negocio para aprovechar puntos',
      description:
          'Reclamar recompensa del negocio para aprovechar puntos acumulados y reforzar fidelidad',
      groupId: 4,
      groupName: 'Fidelización',
      gamificationTypeActivityId: 11,
      gamificationTypeActivityName: 'Marketing',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: true,
      startDate: DateTime(2025, 1, 1, 0, 0),
      endDate: DateTime(2025, 12, 31, 23, 59),
      points: 80,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 169,
      code: 'C2B-31',
      name: 'Participar en reto diario del negocio para ganar beneficios',
      description:
          'Participar en reto diario del negocio para ganar beneficios adicionales y mantener actividad',
      groupId: 4,
      groupName: 'Fidelización',
      gamificationTypeActivityId: 11,
      gamificationTypeActivityName: 'Marketing',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: true,
      startDate: DateTime(2025, 1, 1, 0, 0),
      endDate: DateTime(2025, 12, 31, 23, 59),
      points: 80,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 170,
      code: 'C2B-32',
      name:
          'Participar en evento presencial del negocio para fortalecer comunidad',
      description:
          'Participar en evento presencial del negocio para fortalecer comunidad y relación directa',
      groupId: 4,
      groupName: 'Fidelización',
      gamificationTypeActivityId: 11,
      gamificationTypeActivityName: 'Marketing',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: true,
      startDate: DateTime(2025, 1, 1, 0, 0),
      endDate: DateTime(2025, 12, 31, 23, 59),
      points: 80,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 171,
      code: 'C2B-33',
      name: 'Comprar mensualmente en negocio para mantener fidelidad',
      description:
          'Comprar mensualmente en negocio para mantener fidelidad y acceder beneficios recurrentes',
      groupId: 4,
      groupName: 'Fidelización',
      gamificationTypeActivityId: 11,
      gamificationTypeActivityName: 'Marketing',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: true,
      startDate: DateTime(2025, 1, 1, 0, 0),
      endDate: DateTime(2025, 12, 31, 23, 59),
      points: 80,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 172,
      code: 'C2B-34',
      name: 'Enviar sugerencia al negocio para mejorar servicios',
      description:
          'Enviar sugerencia al negocio para mejorar servicios y aportar ideas ructivas',
      groupId: 4,
      groupName: 'Fidelización',
      gamificationTypeActivityId: 11,
      gamificationTypeActivityName: 'Marketing',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: false,
      startDate: null,
      endDate: null,
      points: 80,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),

    // =====================================================
    // 5) PROMOCIÓN (groupId = 5, 50 puntos)
    // typePoints = "yapitas"
    // =====================================================
    C2BGamificationTask(
      id: 173,
      code: 'C2B-40',
      name: 'Compartir cupón del negocio para atraer clientes',
      description:
          'Compartir cupón del negocio para atraer clientes nuevos y ampliar alcance de la campaña',
      groupId: 5,
      groupName: 'Promoción',
      gamificationTypeActivityId: 1,
      gamificationTypeActivityName: 'Share',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: true,
      startDate: DateTime(2025, 1, 1, 0, 0),
      endDate: DateTime(2025, 12, 31, 23, 59),
      points: 50,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 174,
      code: 'C2B-41',
      name: 'Recomendar producto del negocio para aumentar ventas',
      description:
          'Recomendar producto del negocio para aumentar ventas y generar confianza entre clientes',
      groupId: 5,
      groupName: 'Promoción',
      gamificationTypeActivityId: 3,
      gamificationTypeActivityName: 'Referir',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: false,
      startDate: null,
      endDate: null,
      points: 50,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 175,
      code: 'C2B-42',
      name: 'Invitar usuario a seguir negocio para aumentar comunidad',
      description:
          'Invitar usuario a seguir negocio para aumentar comunidad y fortalecer red de clientes',
      groupId: 5,
      groupName: 'Promoción',
      gamificationTypeActivityId: 3,
      gamificationTypeActivityName: 'Referir',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: false,
      startDate: null,
      endDate: null,
      points: 50,
      typePoints: 'yapitas',
      sourceUrl: null,
    ),

    // =====================================================
    // 6) PREMIUM (groupId = 6, 150 puntos)
    // typePoints = "suma-yapitas"
    // =====================================================
    C2BGamificationTask(
      id: 176,
      code: 'C2B-50',
      name: 'Enviar feedback avanzado al negocio para optimizar fidelización',
      description:
          'Enviar feedback avanzado al negocio para optimizar fidelización y estrategias de servicio',
      groupId: 6,
      groupName: 'Premium',
      gamificationTypeActivityId: 8,
      gamificationTypeActivityName: 'Atención al Cliente',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: true,
      startDate: DateTime(2025, 1, 1, 0, 0),
      endDate: DateTime(2025, 12, 31, 23, 59),
      points: 150,
      typePoints: 'suma-yapitas',
      sourceUrl: null,
    ),
    C2BGamificationTask(
      id: 177,
      code: 'C2B-51',
      name:
          'Participar en campaña de marca del negocio para fortalecer posicionamiento',
      description:
          'Participar en campaña de marca del negocio para fortalecer posicionamiento y alcance digital',
      groupId: 6,
      groupName: 'Premium',
      gamificationTypeActivityId: 11,
      gamificationTypeActivityName: 'Marketing',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: true,
      startDate: DateTime(2025, 1, 1, 0, 0),
      endDate: DateTime(2025, 12, 31, 23, 59),
      points: 150,
      typePoints: 'suma-yapitas',
      sourceUrl: 'https://meetclic.com/campaigns',
    ),
    C2BGamificationTask(
      id: 178,
      code: 'C2B-52',
      name: 'Completar misión especial del negocio para desbloquear beneficios',
      description:
          'Completar misión especial del negocio para desbloquear beneficios exclusivos y recompensas premium',
      groupId: 6,
      groupName: 'Premium',
      gamificationTypeActivityId: 11,
      gamificationTypeActivityName: 'Marketing',
      companyName: 'MeetClic',
      companyId: 1,
      hasExpiration: true,
      startDate: DateTime(2025, 1, 1, 0, 0),
      endDate: DateTime(2025, 12, 31, 23, 59),
      points: 150,
      typePoints: 'suma-yapitas',
      sourceUrl: null,
    ),
  ];
}
